### ISSUE TITLE
download repository 404

### ISSUE THREAD

**Issue by resuarez** [ich777/docker-ungoogled-chromium#1]
The link for download is not longer valid:

[https://github.com/mdedonno1337/ungoogled-chromium-binaries/releases/download/ ](https://github.com/mdedonno1337/ungoogled-chromium-binaries/releases/download/ )
doesn't exist.

But,

[https://github.com/clickot/ungoogled-chromium-binaries/releases/download/ ](https://github.com/clickot/ungoogled-chromium-binaries/releases/download/ )

works

**Comment by ich777** [comment]
Hi, thank you for the report.

Actually that's not entirely true because @mdedonno1337 hasn't compiled the new binary for ungoogled-chromium 98.0.4758.102-1.1
He has only compiled up to version: 95.0.4638.69-1.1 and that's why the download fails, I will look into this tomorrow.

**Comment by ich777** [comment]
@resuarez please update the container, everything is fixed an should work now.

**Comment by resuarez** [comment]
Thank you so much. Great job btw.
