### ISSUE TITLE
Customize noVNC title

### ISSUE THREAD

**Issue by sjtuross** [ich777/docker-ungoogled-chromium#3]
Is it possible to add an environment variable to customize noVNC title? I'd like to change the default title "ungoogle-Chromium - noVNC". Thank you.

**Comment by ich777** [comment]
No, this is not possible.
However you can write a script on the host with the contents:

```
#!/bin/bash
sed -i '/    document.title =/c\    document.title = "WHATEVERYOUWANT";' /usr/share/novnc/app/ui.js
```

and mount it to the container at: `/opt/custom/user.sh`

This script will be executed every container start and will change the title.

Hope that helps.

**Comment by sjtuross** [comment]
Awesome, it works. Thanks for the quick answer!
